project:
  type: website
  output-dir: docs
  render:
    - index.qmd

website:
  title: "it"
  page-navigation: true
  repo-url: https://github.com/eddabbah/it
  repo-actions: [source, issue]
  
  navbar:
    tools: 
      - icon: github
        href: https://github.com/eddabbah/it
        text: GitHub
    left:
      - href: index.qmd
        text: Accueil
         
execute:
  echo: false  

format:
  html:
    theme: cerulean
jupyter: python3
